version: '3.8'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - ./.env.stage.dev
  #   container_name: machrabord-postgres
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machrabord-api
    env_file:
      - ./.env.stage.prod
    http_port:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src