version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env.stage.prod
    container_name: machrabord-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machrabord-api
    env_file:
      - ./.env.stage.prod
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: machrabord-pgadmin4
    env_file:
      - ./.env.stage.prod
    ports:
      - 5050:80
    depends_on:
      - db